### ISSUE TITLE
Tooltip render layer issue

### ISSUE THREAD

**Issue by RookiesTwo** [Kryeit/Missions#48] opened 2024-07-16 14:40 UTC
### Describe the Bug

I am using fabric 1.20.1, mod version is newest release.

In the mission Screen, when the mouse hovers over the missions on the left, the tooltip will be incorrectly rendered below the missions on the right.

![Picture](https://github.com/user-attachments/assets/d24ea51b-ded7-4a48-b7e6-da3585b37df4)

i found if i change language to en_us, the issue does not produce.
i am using Chinese(Simplified), my translation comes from a resource pack loaded with openloader(another mod) ,  i dont know if this helps

### Reproduction Steps

1.use Chinese translation resourcepack loaded with openloader
2.open mission screen
3.hovers over the missions on the left

Resource pack:
[RESOURCEPACK.zip](https://github.com/user-attachments/files/16250658/RESOURCEPACK.zip)

**Comment by muriplz** [comment] 2024-09-09 01:09
![image](https://github.com/user-attachments/assets/7e702bf7-51cd-46a4-9270-0c403519e93a)
![image](https://github.com/user-attachments/assets/a4135e65-c2e9-4a52-8ef2-85ecf7602a26)

**Comment by muriplz** [comment] 2024-09-09 01:09
i cannot reproduce the issue, or am i in the wrong language?

**Comment by muriplz** [comment] 2024-11-12 11:04
i cannot reproduce this so i am closing the issue, if you have a way of reproducing reopen

**Closed as completed by muriplz** 2024-11-12 11:04 UTC
